import type { Metadata } from "next";
import { Shadows_Into_Light_Two, Geist_Mono, Poppins, Inter, Plus_Jakarta_Sans } from "next/font/google";
import Providers from "./providers";
import "./globals.css";

const shadowFont = Shadows_Into_Light_Two( {
  weight   : "400",
  variable : "--font-sans",
  subsets  : ["latin"],
} );

const geistMono = Geist_Mono( {
  variable : "--font-geist-mono",
  subsets  : ["latin"],
} );

const poppins = Poppins( { 
  subsets  : ["latin"], 
  weight   : ["300", "400", "500", "600", "700"],
  variable : "--font-poppins",
} );

const inter = Inter( {
  subsets  : ["latin"],
  weight   : ["300", "400", "500", "600", "700"],
  variable : "--font-inter",
} );

const jakarta = Plus_Jakarta_Sans( {
  subsets  : ["latin"],
  weight   : ["300", "400", "500", "600", "700", "800"],
  variable : "--font-jakarta",
} );

export const metadata: Metadata = {
  title       : "Create Next App",
  description : "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html
      lang="en"
      className={`${shadowFont.variable} ${geistMono.variable} ${poppins.variable} ${inter.variable} ${jakarta.variable} h-full w-screen overflow-hidden antialiased`}
    >
      <body className="h-full flex flex-col overflow-y-auto">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}